loop-timeout: 5s

paloma:
  chain-id: paloma
  call-timeout: 20s
  keyring-dir: ~/.paloma
  keyring-pass-env-name: PALOMA_KEYRING_PASS
  keyring-type: test
  signing-key: my_validator
  base-rpc-url: http://localhost:26657
  gas-adjustment: 2.0
  gas-prices: 0.01grain
  account-prefix: paloma


evm:
  ropsten:
    chain-id: 3
    base-rpc-url: https://ropsten.infura.io/v3/d697ced03e7c49209a1fe2a1c8858821
    keyring-pass-env-name: ROPSTEN_PASS
    signing-key: 0xe4Ab6f4D62Ba7e0bBC4CF6c5E8153e105108FBa9
    keyring-dir: ~/.sparrow/keys/evm/ropsten
    smart-contract-address: 0x16f8B65cB794D20086c1e5309e58C04C39C6eDE9
    gas-adjustment: 2.0
